name: deploy-client

on:
  push:
    branches: 
      - master
    paths:
      -  client/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t emreturgutce/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push emreturgutce/client
    # - uses: digitalocean/action-doctl@v2                        # install doctl tool
    #   with:
    #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}         # using do access token
    # - run: doctl kubernetes cluster kubeconfig save ticketing   # changing cluster to do
    # - run: kubectl rollout restart deployment client-depl         # restarting client-depl