name: deploy-expiration

on:
  push:
    branches: 
      - master
    paths:
      -  expiration/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t emreturgutce/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push emreturgutce/expiration
    # - uses: digitalocean/action-doctl@v2                        # install doctl tool
    #   with:
    #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}         # using do access token
    # - run: doctl kubernetes cluster kubeconfig save ticketing   # changing cluster to do
    # - run: kubectl rollout restart deployment expiration-depl         # restarting expiration-depl